# Generated by Django 5.2.7 on 2025-12-02 09:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_alter_users_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Drivers',
            },
        ),
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('waste_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Waste_types',
            },
        ),
        migrations.CreateModel(
            name='Dumping',
            fields=[
                ('dumping_id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.TextField()),
                ('maximum_capacity', models.IntegerField(blank=True, null=True)),
                ('collected_waste', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.addresses')),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.wastetype')),
            ],
            options={
                'db_table': 'Dumpings',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='scheduled', max_length=20)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='company.driver')),
            ],
            options={
                'db_table': 'Routes',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('pickup_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('inProgress', 'inProgress'), ('completed', 'Completed')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Schedules',
                'unique_together': {('pickup_date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('pickup_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight_collected', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('live_location', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('completed', 'Completed')], default='Not Started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickups', to='company.route')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickups', to='company.schedule')),
            ],
            options={
                'db_table': 'Pickups',
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truck_id', models.AutoField(primary_key=True, serialize=False)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trucks', to='company.driver')),
            ],
            options={
                'db_table': 'Trucks',
            },
        ),
        migrations.AddField(
            model_name='route',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='company.truck'),
        ),
        migrations.AddField(
            model_name='route',
            name='waste_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.wastetype'),
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_passed', models.BooleanField(default=False)),
                ('dumping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.dumping')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='company.route')),
            ],
            options={
                'db_table': 'Route_stops',
                'unique_together': {('route', 'dumping')},
            },
        ),
    ]
