# Generated by Django 5.2.7 on 2025-11-22 15:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_address_alter_companies_address_alter_users_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Drivers',
            },
        ),
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('waste_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Waste_types',
            },
        ),
        migrations.CreateModel(
            name='Dumping',
            fields=[
                ('dumping_id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.TextField()),
                ('maximum_capacity', models.IntegerField(blank=True, null=True)),
                ('collected_waste', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.address')),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.wastetype')),
            ],
            options={
                'db_table': 'Dumpings',
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truck_id', models.AutoField(primary_key=True, serialize=False)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trucks', to='company.driver')),
            ],
            options={
                'db_table': 'Trucks',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='company.driver')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='company.truck')),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.wastetype')),
            ],
            options={
                'db_table': 'Routes',
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_passed', models.BooleanField(default=False)),
                ('dumping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.dumping')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='company.route')),
            ],
            options={
                'db_table': 'Route_stops',
                'unique_together': {('route', 'dumping')},
            },
        ),
    ]
