# Generated by Django 5.2.7 on 2025-11-22 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wastetype',
            table='Waste_Types',
        ),
    ]
