# Generated by Django 5.2.7 on 2025-11-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_wastetype_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wastetype',
            table='Waste_types',
        ),
    ]
