# Generated by Django 5.2.7 on 2025-11-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_route_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('inProgress', 'inProgress'), ('completed', 'Completed')], default='scheduled', max_length=20),
        ),
    ]
