# Generated by Django 5.2.7 on 2025-11-26 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_schedule_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('pickup_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight_collected', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('live_location', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('completed', 'Completed')], default='Not Started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickups', to='company.route')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickups', to='company.schedule')),
            ],
            options={
                'db_table': 'Pickups',
            },
        ),
    ]
