# Generated by Django 5.2.7 on 2025-12-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('inProgress', 'inProgress'), ('completed', 'Completed')], default='available', max_length=20),
        ),
    ]
