# Generated by Django 5.2.7 on 2025-10-25 12:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.TextField()),
                ('city', models.TextField()),
                ('region', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('verification_status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.OneToOneField(blank=True, db_column='address_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.addresses')),
            ],
            options={
                'db_table': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=50)),
                ('can_view', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('role', models.ForeignKey(db_column='role_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.roles')),
            ],
            options={
                'db_table': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_image', models.TextField(blank=True, null=True)),
                ('points_balance', models.IntegerField(default=0)),
                ('account_status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.OneToOneField(blank=True, db_column='address_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.addresses')),
                ('role', models.ForeignKey(db_column='role_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.roles')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
