# Generated by Django 5.2.7 on 2025-11-22 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.TextField()),
                ('city', models.TextField()),
                ('region', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Addresses',
            },
        ),
        migrations.AlterField(
            model_name='companies',
            name='address',
            field=models.OneToOneField(blank=True, db_column='address_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.address'),
        ),
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.OneToOneField(blank=True, db_column='address_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.address'),
        ),
        migrations.DeleteModel(
            name='Addresses',
        ),
    ]
