# Generated by Django 5.2.7 on 2025-11-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='badge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
