# Generated by Django 5.2.7 on 2025-12-04 06:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_users_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('message', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('alert', 'Alert'), ('reward', 'Reward'), ('report', 'Report'), ('system', 'System')], default='system', max_length=50)),
                ('priority', models.CharField(choices=[('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('target_audience', models.CharField(blank=True, max_length=50, null=True)),
                ('target_user_ids', models.JSONField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='authentication.companies')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='authentication.users')),
            ],
            options={
                'db_table': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
