# Generated by Django 5.2.7 on 2025-12-04 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='verification_status',
        ),
    ]
