# Generated by Django 5.2.7 on 2025-12-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='company_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_images/'),
        ),
    ]
