# Generated by Django 5.2.7 on 2025-12-05 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_companies_company_image'),
        ('authentication', '0005_remove_companies_license_number_and_more'),
    ]

    operations = [
    ]
