# Generated by Django 5.2.7 on 2025-12-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_merge_20251205_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='verification_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
