# Generated by Django 5.2.7 on 2025-12-09 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_companies_license_number_and_more'),
    ]

    operations = [
    ]
