# Generated by Django 5.2.7 on 2025-12-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20251209_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='company_image',
            field=models.ImageField(blank=True, null=True, storage='authentication.storage_backend.SupabaseMediaStorage', upload_to='company_images/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage='authentication.storage_backend.SupabaseMediaStorage', upload_to='profile_images/'),
        ),
    ]
