# Generated by Django 5.2.7 on 2025-12-09 22:06

import authentication.storage_backend
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_companies_company_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='company_image',
            field=models.ImageField(blank=True, null=True, storage=authentication.storage_backend.SupabaseMediaStorage(), upload_to='company_images/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=authentication.storage_backend.SupabaseMediaStorage(), upload_to='profile_images/'),
        ),
    ]
