# Generated by Django 5.2.7 on 2025-12-09 22:41

import authentication.storage_backend
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientReports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='image_url',
            field=models.ImageField(blank=True, null=True, storage=authentication.storage_backend.SupabaseMediaStorage(), upload_to='reports/'),
        ),
    ]
