# Generated by Django 5.2.7 on 2025-11-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientReports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='response_priority',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='severity_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='type_of_report',
            field=models.CharField(choices=[('illegal dumping', 'Illegal Dumping'), ('public littering', 'Public Littering'), ('hazardous materials', 'Hazardous Materials'), ('construction debris', 'Construction Debris'), ('organic waste', 'Organic Waste'), ('e-waste', 'E-Waste')], max_length=50),
        ),
    ]
