# Generated by Django 5.2.7 on 2025-11-22 09:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('clientReports', '0002_alter_report_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='address',
        ),
        migrations.RemoveField(
            model_name='report',
            name='handled_by',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('type_of_report', models.CharField(choices=[('illegal dumping', 'Illegal Dumping'), ('public littering', 'Public Littering'), ('hazardous materials', 'Hazardous Materials'), ('construction debris', 'Construction Debris'), ('organic waste', 'Organic Waste'), ('E-waste', 'E-Waste')], max_length=50)),
                ('severity_level', models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], null=True)),
                ('response_priority', models.CharField(blank=True, choices=[('routine', 'Routine'), ('moderate', 'Moderate'), ('high', 'High'), ('emergency', 'Emergency')], max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, db_column='address_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.addresses')),
                ('handled_by', models.ForeignKey(blank=True, db_column='handled_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_reports', to='authentication.users')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='authentication.users')),
            ],
            options={
                'db_table': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
