# Generated by Django 5.2.7 on 2025-11-22 14:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('faq_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='ChatbotLogs',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_text', models.TextField()),
                ('response_text', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.users')),
            ],
            options={
                'db_table': 'ChatbotLogs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
